server:
  addr: "127.0.0.1:33306"


# target mysql
confidential:
  storage: vault # yaml、vault
  vault:
    addr: http://192.168.2.250:18200
    token: myroot
    dataPath: testaaa
  yaml:
    host: 127.0.0.1
    port: 3306
    username: root
    password: root
    dbname: test

fakeIdentity:
  username: test1
  password: test1